/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class EquivEdge : TBase
{

  public PersonID Id1 { get; set; }

  public PersonID Id2 { get; set; }

  public EquivEdge() {
  }

  public EquivEdge(PersonID id1, PersonID id2) : this() {
    this.Id1 = id1;
    this.Id2 = id2;
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      bool isset_id1 = false;
      bool isset_id2 = false;
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              Id1 = new PersonID();
              Id1.Read(iprot);
              isset_id1 = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Struct) {
              Id2 = new PersonID();
              Id2.Read(iprot);
              isset_id2 = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
      if (!isset_id1)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      if (!isset_id2)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("EquivEdge");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      field.Name = "id1";
      field.Type = TType.Struct;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      Id1.Write(oprot);
      oprot.WriteFieldEnd();
      field.Name = "id2";
      field.Type = TType.Struct;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      Id2.Write(oprot);
      oprot.WriteFieldEnd();
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("EquivEdge(");
    __sb.Append(", Id1: ");
    __sb.Append(Id1== null ? "<null>" : Id1.ToString());
    __sb.Append(", Id2: ");
    __sb.Append(Id2== null ? "<null>" : Id2.ToString());
    __sb.Append(")");
    return __sb.ToString();
  }

}

